In [6]:
import pandas as pd
from scipy.io import arff

file_path = 'KDDTest+.arff'

# Загружаем ARFF-файл
# Функция loadarff возвращает кортеж: (данные, метаданные)
data, meta = arff.loadarff(file_path)

In [12]:
df = pd.DataFrame(data, columns=meta.names())
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0.0,b'tcp',b'private',b'REJ',0.0,0.0,b'0',0.0,0.0,0.0,...,10.0,0.04,0.06,0.00,0.00,0.0,0.0,1.00,1.00,b'anomaly'
1,0.0,b'tcp',b'private',b'REJ',0.0,0.0,b'0',0.0,0.0,0.0,...,1.0,0.00,0.06,0.00,0.00,0.0,0.0,1.00,1.00,b'anomaly'
2,2.0,b'tcp',b'ftp_data',b'SF',12983.0,0.0,b'0',0.0,0.0,0.0,...,86.0,0.61,0.04,0.61,0.02,0.0,0.0,0.00,0.00,b'normal'
3,0.0,b'icmp',b'eco_i',b'SF',20.0,0.0,b'0',0.0,0.0,0.0,...,57.0,1.00,0.00,1.00,0.28,0.0,0.0,0.00,0.00,b'anomaly'
4,1.0,b'tcp',b'telnet',b'RSTO',0.0,15.0,b'0',0.0,0.0,0.0,...,86.0,0.31,0.17,0.03,0.02,0.0,0.0,0.83,0.71,b'anomaly'

In [13]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
encoder.fit(df[["protocol_type"]])
X_train_encoded = encoder.transform(df[["protocol_type"]])

In [18]:
df[["protocol_type"]]

      protocol_type
0            b'tcp'
1            b'tcp'
2            b'tcp'
3           b'icmp'
4            b'tcp'
...             ...
22539        b'tcp'
22540        b'tcp'
22541        b'tcp'
22542        b'udp'
22543        b'tcp'

[22544 rows x 1 columns]

In [16]:
X_train_encoded

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], shape=(22544, 3))

In [24]:
df["normal_class"] = (df["class"] != b"normal").astype(int)   # 0 = норма, 1 = атака
print(df["normal_class"].value_counts())
print("Типов атак в class:", df["class"].nunique() - 1)

normal_class
1    12833
0     9711
Name: count, dtype: int64
Типов атак в class: 1

In [36]:
x = df.drop(columns=["class", "normal_class", 'X'])
y = df["normal_class"]

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y,random_state=42)

In [41]:
y_test

21075    1
8475     1
21743    1
9327     1
2527     1
        ..
15139    1
16407    0
13153    0
4460     1
18227    1
Name: normal_class, Length: 4509, dtype: int64